spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:devdb
    username: dev
    password: 12345
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080